export type Confederation = 'AFC' | 'CAF' | 'CONCACAF' | 'CONMEBOL' | 'OFC' | 'UEFA'

export interface FifaMemberAssociation {
  id: string
  name: string
  flag: string
  confederation: Confederation
  apiFootballAliases?: string[]
}

// FIFA currently describes its membership as 211 member associations across six confederations.
export const fifaMemberAssociations: FifaMemberAssociation[] = [
  { id: 'afghanistan', name: 'Afghanistan', flag: '🇦🇫', confederation: 'AFC' },
  { id: 'australia', name: 'Australia', flag: '🇦🇺', confederation: 'AFC' },
  { id: 'bahrain', name: 'Bahrain', flag: '🇧🇭', confederation: 'AFC' },
  { id: 'bangladesh', name: 'Bangladesh', flag: '🇧🇩', confederation: 'AFC' },
  { id: 'bhutan', name: 'Bhutan', flag: '🇧🇹', confederation: 'AFC' },
  { id: 'brunei-darussalam', name: 'Brunei Darussalam', flag: '🇧🇳', confederation: 'AFC' },
  { id: 'cambodia', name: 'Cambodia', flag: '🇰🇭', confederation: 'AFC' },
  { id: 'china-pr', name: 'China PR', flag: '🇨🇳', confederation: 'AFC', apiFootballAliases: ['China'] },
  { id: 'chinese-taipei', name: 'Chinese Taipei', flag: '🇹🇼', confederation: 'AFC', apiFootballAliases: ['Taiwan'] },
  { id: 'guam', name: 'Guam', flag: '🇬🇺', confederation: 'AFC' },
  { id: 'hong-kong-china', name: 'Hong Kong China', flag: '🇭🇰', confederation: 'AFC', apiFootballAliases: ['Hong Kong'] },
  { id: 'india', name: 'India', flag: '🇮🇳', confederation: 'AFC' },
  { id: 'indonesia', name: 'Indonesia', flag: '🇮🇩', confederation: 'AFC' },
  { id: 'iran', name: 'Iran', flag: '🇮🇷', confederation: 'AFC' },
  { id: 'iraq', name: 'Iraq', flag: '🇮🇶', confederation: 'AFC' },
  { id: 'japan', name: 'Japan', flag: '🇯🇵', confederation: 'AFC' },
  { id: 'jordan', name: 'Jordan', flag: '🇯🇴', confederation: 'AFC' },
  { id: 'korea-dpr', name: 'Korea DPR', flag: '🇰🇵', confederation: 'AFC', apiFootballAliases: ['North Korea'] },
  { id: 'korea-republic', name: 'Korea Republic', flag: '🇰🇷', confederation: 'AFC', apiFootballAliases: ['South Korea'] },
  { id: 'kuwait', name: 'Kuwait', flag: '🇰🇼', confederation: 'AFC' },
  { id: 'kyrgyz-republic', name: 'Kyrgyz Republic', flag: '🇰🇬', confederation: 'AFC', apiFootballAliases: ['Kyrgyzstan'] },
  { id: 'laos', name: 'Laos', flag: '🇱🇦', confederation: 'AFC' },
  { id: 'lebanon', name: 'Lebanon', flag: '🇱🇧', confederation: 'AFC' },
  { id: 'macau', name: 'Macau', flag: '🇲🇴', confederation: 'AFC' },
  { id: 'malaysia', name: 'Malaysia', flag: '🇲🇾', confederation: 'AFC' },
  { id: 'maldives', name: 'Maldives', flag: '🇲🇻', confederation: 'AFC' },
  { id: 'mongolia', name: 'Mongolia', flag: '🇲🇳', confederation: 'AFC' },
  { id: 'myanmar', name: 'Myanmar', flag: '🇲🇲', confederation: 'AFC' },
  { id: 'nepal', name: 'Nepal', flag: '🇳🇵', confederation: 'AFC' },
  { id: 'oman', name: 'Oman', flag: '🇴🇲', confederation: 'AFC' },
  { id: 'pakistan', name: 'Pakistan', flag: '🇵🇰', confederation: 'AFC' },
  { id: 'palestine', name: 'Palestine', flag: '🇵🇸', confederation: 'AFC' },
  { id: 'philippines', name: 'Philippines', flag: '🇵🇭', confederation: 'AFC' },
  { id: 'qatar', name: 'Qatar', flag: '🇶🇦', confederation: 'AFC' },
  { id: 'saudi-arabia', name: 'Saudi Arabia', flag: '🇸🇦', confederation: 'AFC' },
  { id: 'singapore', name: 'Singapore', flag: '🇸🇬', confederation: 'AFC' },
  { id: 'sri-lanka', name: 'Sri Lanka', flag: '🇱🇰', confederation: 'AFC' },
  { id: 'syria', name: 'Syria', flag: '🇸🇾', confederation: 'AFC' },
  { id: 'tajikistan', name: 'Tajikistan', flag: '🇹🇯', confederation: 'AFC' },
  { id: 'thailand', name: 'Thailand', flag: '🇹🇭', confederation: 'AFC' },
  { id: 'timor-leste', name: 'Timor-Leste', flag: '🇹🇱', confederation: 'AFC' },
  { id: 'turkmenistan', name: 'Turkmenistan', flag: '🇹🇲', confederation: 'AFC' },
  { id: 'united-arab-emirates', name: 'United Arab Emirates', flag: '🇦🇪', confederation: 'AFC', apiFootballAliases: ['United Arab Emirates UAE'] },
  { id: 'uzbekistan', name: 'Uzbekistan', flag: '🇺🇿', confederation: 'AFC' },
  { id: 'vietnam', name: 'Vietnam', flag: '🇻🇳', confederation: 'AFC' },
  { id: 'yemen', name: 'Yemen', flag: '🇾🇪', confederation: 'AFC' },

  { id: 'algeria', name: 'Algeria', flag: '🇩🇿', confederation: 'CAF' },
  { id: 'angola', name: 'Angola', flag: '🇦🇴', confederation: 'CAF' },
  { id: 'benin', name: 'Benin', flag: '🇧🇯', confederation: 'CAF' },
  { id: 'botswana', name: 'Botswana', flag: '🇧🇼', confederation: 'CAF' },
  { id: 'burkina-faso', name: 'Burkina Faso', flag: '🇧🇫', confederation: 'CAF' },
  { id: 'burundi', name: 'Burundi', flag: '🇧🇮', confederation: 'CAF' },
  { id: 'cameroon', name: 'Cameroon', flag: '🇨🇲', confederation: 'CAF' },
  { id: 'cabo-verde', name: 'Cabo Verde', flag: '🇨🇻', confederation: 'CAF', apiFootballAliases: ['Cape Verde'] },
  { id: 'central-african-republic', name: 'Central African Republic', flag: '🇨🇫', confederation: 'CAF' },
  { id: 'chad', name: 'Chad', flag: '🇹🇩', confederation: 'CAF' },
  { id: 'comoros', name: 'Comoros', flag: '🇰🇲', confederation: 'CAF' },
  { id: 'congo', name: 'Congo', flag: '🇨🇬', confederation: 'CAF' },
  { id: 'congo-dr', name: 'Congo DR', flag: '🇨🇩', confederation: 'CAF', apiFootballAliases: ['DR Congo'] },
  { id: 'cote-divoire', name: 'Côte d\'Ivoire', flag: '🇨🇮', confederation: 'CAF', apiFootballAliases: ['Ivory Coast'] },
  { id: 'djibouti', name: 'Djibouti', flag: '🇩🇯', confederation: 'CAF' },
  { id: 'egypt', name: 'Egypt', flag: '🇪🇬', confederation: 'CAF' },
  { id: 'equatorial-guinea', name: 'Equatorial Guinea', flag: '🇬🇶', confederation: 'CAF' },
  { id: 'eritrea', name: 'Eritrea', flag: '🇪🇷', confederation: 'CAF' },
  { id: 'eswatini', name: 'Eswatini', flag: '🇸🇿', confederation: 'CAF', apiFootballAliases: ['Swaziland'] },
  { id: 'ethiopia', name: 'Ethiopia', flag: '🇪🇹', confederation: 'CAF' },
  { id: 'gabon', name: 'Gabon', flag: '🇬🇦', confederation: 'CAF' },
  { id: 'gambia', name: 'Gambia', flag: '🇬🇲', confederation: 'CAF' },
  { id: 'ghana', name: 'Ghana', flag: '🇬🇭', confederation: 'CAF' },
  { id: 'guinea', name: 'Guinea', flag: '🇬🇳', confederation: 'CAF' },
  { id: 'guinea-bissau', name: 'Guinea-Bissau', flag: '🇬🇼', confederation: 'CAF' },
  { id: 'kenya', name: 'Kenya', flag: '🇰🇪', confederation: 'CAF' },
  { id: 'lesotho', name: 'Lesotho', flag: '🇱🇸', confederation: 'CAF' },
  { id: 'liberia', name: 'Liberia', flag: '🇱🇷', confederation: 'CAF' },
  { id: 'libya', name: 'Libya', flag: '🇱🇾', confederation: 'CAF' },
  { id: 'madagascar', name: 'Madagascar', flag: '🇲🇬', confederation: 'CAF' },
  { id: 'malawi', name: 'Malawi', flag: '🇲🇼', confederation: 'CAF' },
  { id: 'mali', name: 'Mali', flag: '🇲🇱', confederation: 'CAF' },
  { id: 'mauritania', name: 'Mauritania', flag: '🇲🇷', confederation: 'CAF' },
  { id: 'mauritius', name: 'Mauritius', flag: '🇲🇺', confederation: 'CAF' },
  { id: 'morocco', name: 'Morocco', flag: '🇲🇦', confederation: 'CAF' },
  { id: 'mozambique', name: 'Mozambique', flag: '🇲🇿', confederation: 'CAF' },
  { id: 'namibia', name: 'Namibia', flag: '🇳🇦', confederation: 'CAF' },
  { id: 'niger', name: 'Niger', flag: '🇳🇪', confederation: 'CAF' },
  { id: 'nigeria', name: 'Nigeria', flag: '🇳🇬', confederation: 'CAF' },
  { id: 'rwanda', name: 'Rwanda', flag: '🇷🇼', confederation: 'CAF' },
  { id: 'sao-tome-and-principe', name: 'Sao Tome and Principe', flag: '🇸🇹', confederation: 'CAF', apiFootballAliases: ['São Tomé and Príncipe'] },
  { id: 'senegal', name: 'Senegal', flag: '🇸🇳', confederation: 'CAF' },
  { id: 'seychelles', name: 'Seychelles', flag: '🇸🇨', confederation: 'CAF' },
  { id: 'sierra-leone', name: 'Sierra Leone', flag: '🇸🇱', confederation: 'CAF' },
  { id: 'somalia', name: 'Somalia', flag: '🇸🇴', confederation: 'CAF' },
  { id: 'south-africa', name: 'South Africa', flag: '🇿🇦', confederation: 'CAF' },
  { id: 'south-sudan', name: 'South Sudan', flag: '🇸🇸', confederation: 'CAF' },
  { id: 'sudan', name: 'Sudan', flag: '🇸🇩', confederation: 'CAF' },
  { id: 'tanzania', name: 'Tanzania', flag: '🇹🇿', confederation: 'CAF' },
  { id: 'togo', name: 'Togo', flag: '🇹🇬', confederation: 'CAF' },
  { id: 'tunisia', name: 'Tunisia', flag: '🇹🇳', confederation: 'CAF' },
  { id: 'uganda', name: 'Uganda', flag: '🇺🇬', confederation: 'CAF' },
  { id: 'zambia', name: 'Zambia', flag: '🇿🇲', confederation: 'CAF' },
  { id: 'zimbabwe', name: 'Zimbabwe', flag: '🇿🇼', confederation: 'CAF' },

  { id: 'anguilla', name: 'Anguilla', flag: '🇦🇮', confederation: 'CONCACAF' },
  { id: 'antigua-and-barbuda', name: 'Antigua and Barbuda', flag: '🇦🇬', confederation: 'CONCACAF' },
  { id: 'aruba', name: 'Aruba', flag: '🇦🇼', confederation: 'CONCACAF' },
  { id: 'bahamas', name: 'Bahamas', flag: '🇧🇸', confederation: 'CONCACAF' },
  { id: 'barbados', name: 'Barbados', flag: '🇧🇧', confederation: 'CONCACAF' },
  { id: 'belize', name: 'Belize', flag: '🇧🇿', confederation: 'CONCACAF' },
  { id: 'bermuda', name: 'Bermuda', flag: '🇧🇲', confederation: 'CONCACAF' },
  { id: 'british-virgin-islands', name: 'British Virgin Islands', flag: '🇻🇬', confederation: 'CONCACAF' },
  { id: 'canada', name: 'Canada', flag: '🇨🇦', confederation: 'CONCACAF' },
  { id: 'cayman-islands', name: 'Cayman Islands', flag: '🇰🇾', confederation: 'CONCACAF' },
  { id: 'costa-rica', name: 'Costa Rica', flag: '🇨🇷', confederation: 'CONCACAF' },
  { id: 'cuba', name: 'Cuba', flag: '🇨🇺', confederation: 'CONCACAF' },
  { id: 'curacao', name: 'Curaçao', flag: '🇨🇼', confederation: 'CONCACAF' },
  { id: 'dominica', name: 'Dominica', flag: '🇩🇲', confederation: 'CONCACAF' },
  { id: 'dominican-republic', name: 'Dominican Republic', flag: '🇩🇴', confederation: 'CONCACAF' },
  { id: 'el-salvador', name: 'El Salvador', flag: '🇸🇻', confederation: 'CONCACAF' },
  { id: 'grenada', name: 'Grenada', flag: '🇬🇩', confederation: 'CONCACAF' },
  { id: 'guatemala', name: 'Guatemala', flag: '🇬🇹', confederation: 'CONCACAF' },
  { id: 'guyana', name: 'Guyana', flag: '🇬🇾', confederation: 'CONCACAF' },
  { id: 'haiti', name: 'Haiti', flag: '🇭🇹', confederation: 'CONCACAF' },
  { id: 'honduras', name: 'Honduras', flag: '🇭🇳', confederation: 'CONCACAF' },
  { id: 'jamaica', name: 'Jamaica', flag: '🇯🇲', confederation: 'CONCACAF' },
  { id: 'mexico', name: 'Mexico', flag: '🇲🇽', confederation: 'CONCACAF' },
  { id: 'montserrat', name: 'Montserrat', flag: '🇲🇸', confederation: 'CONCACAF' },
  { id: 'nicaragua', name: 'Nicaragua', flag: '🇳🇮', confederation: 'CONCACAF' },
  { id: 'panama', name: 'Panama', flag: '🇵🇦', confederation: 'CONCACAF' },
  { id: 'puerto-rico', name: 'Puerto Rico', flag: '🇵🇷', confederation: 'CONCACAF' },
  { id: 'saint-kitts-and-nevis', name: 'Saint Kitts and Nevis', flag: '🇰🇳', confederation: 'CONCACAF' },
  { id: 'saint-lucia', name: 'Saint Lucia', flag: '🇱🇨', confederation: 'CONCACAF' },
  { id: 'saint-vincent-and-the-grenadines', name: 'Saint Vincent and the Grenadines', flag: '🇻🇨', confederation: 'CONCACAF' },
  { id: 'suriname', name: 'Suriname', flag: '🇸🇷', confederation: 'CONCACAF' },
  { id: 'trinidad-and-tobago', name: 'Trinidad and Tobago', flag: '🇹🇹', confederation: 'CONCACAF' },
  { id: 'turks-and-caicos-islands', name: 'Turks and Caicos Islands', flag: '🇹🇨', confederation: 'CONCACAF' },
  { id: 'us-virgin-islands', name: 'U.S. Virgin Islands', flag: '🇻🇮', confederation: 'CONCACAF' },
  { id: 'usa', name: 'USA', flag: '🇺🇸', confederation: 'CONCACAF', apiFootballAliases: ['United States'] },

  { id: 'argentina', name: 'Argentina', flag: '🇦🇷', confederation: 'CONMEBOL' },
  { id: 'bolivia', name: 'Bolivia', flag: '🇧🇴', confederation: 'CONMEBOL' },
  { id: 'brazil', name: 'Brazil', flag: '🇧🇷', confederation: 'CONMEBOL' },
  { id: 'chile', name: 'Chile', flag: '🇨🇱', confederation: 'CONMEBOL' },
  { id: 'colombia', name: 'Colombia', flag: '🇨🇴', confederation: 'CONMEBOL' },
  { id: 'ecuador', name: 'Ecuador', flag: '🇪🇨', confederation: 'CONMEBOL' },
  { id: 'paraguay', name: 'Paraguay', flag: '🇵🇾', confederation: 'CONMEBOL' },
  { id: 'peru', name: 'Peru', flag: '🇵🇪', confederation: 'CONMEBOL' },
  { id: 'uruguay', name: 'Uruguay', flag: '🇺🇾', confederation: 'CONMEBOL' },
  { id: 'venezuela', name: 'Venezuela', flag: '🇻🇪', confederation: 'CONMEBOL' },

  { id: 'american-samoa', name: 'American Samoa', flag: '🇦🇸', confederation: 'OFC' },
  { id: 'cook-islands', name: 'Cook Islands', flag: '🇨🇰', confederation: 'OFC' },
  { id: 'fiji', name: 'Fiji', flag: '🇫🇯', confederation: 'OFC' },
  { id: 'new-caledonia', name: 'New Caledonia', flag: '🇳🇨', confederation: 'OFC' },
  { id: 'new-zealand', name: 'New Zealand', flag: '🇳🇿', confederation: 'OFC' },
  { id: 'papua-new-guinea', name: 'Papua New Guinea', flag: '🇵🇬', confederation: 'OFC' },
  { id: 'samoa', name: 'Samoa', flag: '🇼🇸', confederation: 'OFC' },
  { id: 'solomon-islands', name: 'Solomon Islands', flag: '🇸🇧', confederation: 'OFC' },
  { id: 'tahiti', name: 'Tahiti', flag: '🇵🇫', confederation: 'OFC', apiFootballAliases: ['French Polynesia'] },
  { id: 'tonga', name: 'Tonga', flag: '🇹🇴', confederation: 'OFC' },
  { id: 'vanuatu', name: 'Vanuatu', flag: '🇻🇺', confederation: 'OFC' },

  { id: 'albania', name: 'Albania', flag: '🇦🇱', confederation: 'UEFA' },
  { id: 'andorra', name: 'Andorra', flag: '🇦🇩', confederation: 'UEFA' },
  { id: 'armenia', name: 'Armenia', flag: '🇦🇲', confederation: 'UEFA' },
  { id: 'austria', name: 'Austria', flag: '🇦🇹', confederation: 'UEFA' },
  { id: 'azerbaijan', name: 'Azerbaijan', flag: '🇦🇿', confederation: 'UEFA' },
  { id: 'belarus', name: 'Belarus', flag: '🇧🇾', confederation: 'UEFA' },
  { id: 'belgium', name: 'Belgium', flag: '🇧🇪', confederation: 'UEFA' },
  { id: 'bosnia-and-herzegovina', name: 'Bosnia and Herzegovina', flag: '🇧🇦', confederation: 'UEFA', apiFootballAliases: ['Bosnia & Herzegovina'] },
  { id: 'bulgaria', name: 'Bulgaria', flag: '🇧🇬', confederation: 'UEFA' },
  { id: 'croatia', name: 'Croatia', flag: '🇭🇷', confederation: 'UEFA' },
  { id: 'cyprus', name: 'Cyprus', flag: '🇨🇾', confederation: 'UEFA' },
  { id: 'czechia', name: 'Czechia', flag: '🇨🇿', confederation: 'UEFA', apiFootballAliases: ['Czech Republic'] },
  { id: 'denmark', name: 'Denmark', flag: '🇩🇰', confederation: 'UEFA' },
  { id: 'england', name: 'England', flag: '🏴', confederation: 'UEFA' },
  { id: 'estonia', name: 'Estonia', flag: '🇪🇪', confederation: 'UEFA' },
  { id: 'faroe-islands', name: 'Faroe Islands', flag: '🇫🇴', confederation: 'UEFA' },
  { id: 'finland', name: 'Finland', flag: '🇫🇮', confederation: 'UEFA' },
  { id: 'france', name: 'France', flag: '🇫🇷', confederation: 'UEFA' },
  { id: 'georgia', name: 'Georgia', flag: '🇬🇪', confederation: 'UEFA' },
  { id: 'germany', name: 'Germany', flag: '🇩🇪', confederation: 'UEFA' },
  { id: 'gibraltar', name: 'Gibraltar', flag: '🇬🇮', confederation: 'UEFA' },
  { id: 'greece', name: 'Greece', flag: '🇬🇷', confederation: 'UEFA' },
  { id: 'hungary', name: 'Hungary', flag: '🇭🇺', confederation: 'UEFA' },
  { id: 'iceland', name: 'Iceland', flag: '🇮🇸', confederation: 'UEFA' },
  { id: 'ireland', name: 'Ireland', flag: '🇮🇪', confederation: 'UEFA', apiFootballAliases: ['Republic of Ireland'] },
  { id: 'israel', name: 'Israel', flag: '🇮🇱', confederation: 'UEFA' },
  { id: 'italy', name: 'Italy', flag: '🇮🇹', confederation: 'UEFA' },
  { id: 'kazakhstan', name: 'Kazakhstan', flag: '🇰🇿', confederation: 'UEFA' },
  { id: 'kosovo', name: 'Kosovo', flag: '🇽🇰', confederation: 'UEFA' },
  { id: 'latvia', name: 'Latvia', flag: '🇱🇻', confederation: 'UEFA' },
  { id: 'liechtenstein', name: 'Liechtenstein', flag: '🇱🇮', confederation: 'UEFA' },
  { id: 'lithuania', name: 'Lithuania', flag: '🇱🇹', confederation: 'UEFA' },
  { id: 'luxembourg', name: 'Luxembourg', flag: '🇱🇺', confederation: 'UEFA' },
  { id: 'malta', name: 'Malta', flag: '🇲🇹', confederation: 'UEFA' },
  { id: 'moldova', name: 'Moldova', flag: '🇲🇩', confederation: 'UEFA' },
  { id: 'montenegro', name: 'Montenegro', flag: '🇲🇪', confederation: 'UEFA' },
  { id: 'netherlands', name: 'Netherlands', flag: '🇳🇱', confederation: 'UEFA' },
  { id: 'north-macedonia', name: 'North Macedonia', flag: '🇲🇰', confederation: 'UEFA' },
  { id: 'northern-ireland', name: 'Northern Ireland', flag: '🇬🇧', confederation: 'UEFA' },
  { id: 'norway', name: 'Norway', flag: '🇳🇴', confederation: 'UEFA' },
  { id: 'poland', name: 'Poland', flag: '🇵🇱', confederation: 'UEFA' },
  { id: 'portugal', name: 'Portugal', flag: '🇵🇹', confederation: 'UEFA' },
  { id: 'romania', name: 'Romania', flag: '🇷🇴', confederation: 'UEFA' },
  { id: 'russia', name: 'Russia', flag: '🇷🇺', confederation: 'UEFA' },
  { id: 'san-marino', name: 'San Marino', flag: '🇸🇲', confederation: 'UEFA' },
  { id: 'scotland', name: 'Scotland', flag: '🏴', confederation: 'UEFA' },
  { id: 'serbia', name: 'Serbia', flag: '🇷🇸', confederation: 'UEFA' },
  { id: 'slovakia', name: 'Slovakia', flag: '🇸🇰', confederation: 'UEFA' },
  { id: 'slovenia', name: 'Slovenia', flag: '🇸🇮', confederation: 'UEFA' },
  { id: 'spain', name: 'Spain', flag: '🇪🇸', confederation: 'UEFA' },
  { id: 'sweden', name: 'Sweden', flag: '🇸🇪', confederation: 'UEFA' },
  { id: 'switzerland', name: 'Switzerland', flag: '🇨🇭', confederation: 'UEFA' },
  { id: 'turkiye', name: 'Türkiye', flag: '🇹🇷', confederation: 'UEFA', apiFootballAliases: ['Turkey'] },
  { id: 'ukraine', name: 'Ukraine', flag: '🇺🇦', confederation: 'UEFA' },
  { id: 'wales', name: 'Wales', flag: '🏴', confederation: 'UEFA' },
]
